development: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: edogawa3
  database: school_dev
  pool: 5
  timeout: 5000

test:
  <<: *defaults
  database: school_test

production:
  <<: *defaults
  database: school_prod